[build-system]
requires = [ "setuptools>=60", "wheel", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mapp"
dynamic = ["version"]
dependencies = ["ngapp"]

[tool.setuptools.packages.find]
where = ["src"]
